using System.Net.Http.Headers;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using Dapr.Client;
using Newtonsoft.Json;
using JsonSerializer = System.Text.Json.JsonSerializer;
using checkout;


//var client = DaprClient.CreateInvokeHttpClient("hms-maui-aggregatorsvc", "http://localhost:3500/");
var client = DaprClient.CreateInvokeHttpClient(" hms-maui-usersvc", "http://localhost:5032/");

var authToken = @"eyJhbGciOiJSUzI1NiIsImtpZCI6InBzSVRWcEtib0dWTHFycGhiS2dIbWRMbXVlQ3hTdV9KcXRUTjRsMUNncTAiLCJ0eXAiOiJKV1QifQ.eyJvaWQiOiI5ZGI5NDExZS1jMDhjLTQ3ZjQtOWMyOC04MDEwNmUwZTY2ZDMiLCJzdWIiOiJOb3Qgc3VwcG9ydGVkIGN1cnJlbnRseS4gVXNlIG9pZCBjbGFpbS4iLCJlbWFpbCI6Im1hdWlkc3AyQHlvcG1haWwuY29tIiwiWmVpc3NJZEJhc2UiOiJ7XHJcbiAgXCJhY2NvdW50SWRcIjogNDc4NTMyLFxyXG4gIFwiZmlyc3ROYW1lXCI6IFwiTWF1aVwiLFxyXG4gIFwibGFzdE5hbWVcIjogXCJUZXN0XCIsXHJcbiAgXCJlTWFpbFwiOiBcIm1hdWlkc3AyQHlvcG1haWwuY29tXCIsXHJcbiAgXCJsYXN0Q2hhbmdlXCI6IFwiMjAyMy0wMi0yMVQwNzowNzoxMC4yOFwiLFxyXG4gIFwiaWRlbnRpdHlQcm92aWRlclwiOiAxLFxyXG4gIFwiam9iVGl0bGVcIjogXCJcIixcclxuICBcImRlcGFydG1lbnRcIjogXCJcIixcclxuICBcInNhbHV0YXRpb25cIjogXCJuYVwiLFxyXG4gIFwibGFuZ3VhZ2VcIjogXCJlblwiLFxyXG4gIFwiZGF0ZU9mQmlydGhcIjogXCJcIlxyXG59IiwiWmVpc3NJZENvbnRhY3QiOiJ7XHJcbiAgXCJzdHJlZXRcIjogXCJcIixcclxuICBcImhvdXNlTnVtYmVyXCI6IFwiXCIsXHJcbiAgXCJ6aXBcIjogXCJcIixcclxuICBcImNpdHlcIjogXCJcIixcclxuICBcImNvdW50cnlcIjogXCJJTlwiLFxyXG4gIFwiY2VsbFBob25lXCI6IFwiXCIsXHJcbiAgXCJwaG9uZVwiOiBcIlwiLFxyXG4gIFwiZmF4XCI6IFwiXCJcclxufSIsIlplaXNzSWRPcmdhbmlzYXRpb24iOiJ7XHJcbiAgXCJvcmdhbmlzYXRpb25JZFwiOiA2NTAxOCxcclxuICBcIm5hbWVcIjogXCJaRUlTUyBBR1wiLFxyXG4gIFwic3RyZWV0XCI6IFwiXCIsXHJcbiAgXCJob3VzZU51bWJlclwiOiBcIlwiLFxyXG4gIFwiY2l0eVwiOiBcIlwiLFxyXG4gIFwiemlwXCI6IFwiXCIsXHJcbiAgXCJjb3VudHJ5XCI6IFwiQ0hcIixcclxuICBcInplaXNzQ3VzdG9tZXJOb1wiOiBudWxsLFxyXG4gIFwiemVpc3NTZWNvbmRhcnlSZWZlcmVuY2VcIjogbnVsbCxcclxuICBcInplaXNzM3JkUGFydHlTeXN0ZW1cIjogbnVsbCxcclxuICBcImxhc3RDaGFuZ2VcIjogXCIyMDE5LTA2LTE0VDE1OjE3OjM2Ljk2XCIsXHJcbiAgXCJmZWRlcmFsU3RhdGVcIjogXCJcIixcclxuICBcImdyb3VwXCI6IGZhbHNlLFxyXG4gIFwicGFyZW50T3JnYW5pc2F0aW9uSWRcIjogbnVsbCxcclxuICBcIm9yZ2FuaXNhdGlvblZlcmlmaWNhdGlvblwiOiAwXHJcbn0iLCJaZWlzc0lkQXBwbGljYXRpb24iOiJ7XHJcbiAgXCJjbGllbnRBcHBJZFwiOiA0MDYsXHJcbiAgXCJhcHBsaWNhdGlvbkRvbWFpbklkXCI6IDUsXHJcbiAgXCJ0ZXJtc0FuZENvbmRpdGlvbnNJZFwiOiAwLFxyXG4gIFwiYWNjZXB0YW5jZU9mVGVybXNBbmRDb25kaXRpb25zSWRcIjogMCxcclxuICBcImRpcmVjdEFjY2Vzc1wiOiBmYWxzZSxcclxuICBcImludml0YXRpb25JZFwiOiAyODM2NTlcclxufSIsIlplaXNzSWRDdXN0b21GaWVsZHMiOiJ7fSIsIlplaXNzSWRBZ3JlZW1lbnRzIjoie1xyXG4gIFwiYWdyZWVtZW50c1wiOiBbXHJcbiAgICB7XHJcbiAgICAgIFwiYWdyZWVtZW50SWRcIjogMTAzMzMsXHJcbiAgICAgIFwiaXNBZ3JlZW1lbnRNYW5hZ2VyXCI6IGZhbHNlXHJcbiAgICB9XHJcbiAgXVxyXG59IiwiZ2V0TW9yZUNsYWltcyI6IiIsImF6cCI6IjIyNTg1NDFhLWYwZDMtNGU3MS1iYWI1LWZkYjYzMjBmYjkyMiIsInZlciI6IjEuMCIsImlhdCI6MTY4NDMyNDg1MSwiYXVkIjoiMjI1ODU0MWEtZjBkMy00ZTcxLWJhYjUtZmRiNjMyMGZiOTIyIiwiZXhwIjoxNjg0MzI4NDUxLCJpc3MiOiJodHRwczovL2IyY3N0YWdlLnplaXNzLmNvbS80ODNmNDQ5Yi02YTBkLTQzNTQtYjdlNy0zNzExM2U3ZDRjYTEvdjIuMC8iLCJuYmYiOjE2ODQzMjQ4NTF9.em6WAhD-zx6co-liAyOCxY4EFl83tduJSDW2kB96kYjHj68Kw3nbu--SUSNtMrwEWGgEMIUa4-1BijE--eAxCexxAHeHWoxtLP2_LmRJe-7dZ9b9ip8kOUVyi-kuyEcUQrwJt1fSCQtgy8RfY3eVUnJokjrx1Krl1ZnQZjWWFRrgcXxcYXzlOu7MYQIKoIgZJvp2pxVKwa8X8nggX72jqY_FWRIhTfSSWrHpOqcZAG8y08GDVJoeiWc6EbGviy88SDcsUbMfzuwcAiXPYrwSJ0fdzxxzuSim5YLkEYquhDCiBxmo5DssR0kePLHQuoXQ0_LBi0zBs_8gOfgxGgtHig";
//client.DefaultRequestHeaders.Add("dapr-app-id", );
client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", authToken);

//var order = new EventChatQueryDto();

//order.EventId = 1;

GetUsersByUserIdsRequestDto order = new GetUsersByUserIdsRequestDto();
order.UserIds = new List<int>();
order.UserIds.Add(12);
order.UserIds.Add(7);

//var orderJson = JsonSerializer.Serialize<EventChatQueryDto>(order);

var orderJson = JsonSerializer.Serialize<GetUsersByUserIdsRequestDto>(order);
var content = new StringContent(orderJson, Encoding.UTF8, "application/json");

//var response = await client.PostAsync(@"Aggregator/GetAllChats", content);
var response = await client.PostAsync(@"User/GetAllChats", content);
Console.WriteLine("Order response: \n" + response.ToString());

Console.WriteLine("Order passed: \n" + response.Content.ReadAsStringAsync().GetAwaiter().GetResult());

await Task.Delay(TimeSpan.FromSeconds(1));
